// <auto-generated />
using System;
using IQ.Accountant.System.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IQ.Accountant.System.Model.Migrations
{
    [DbContext(typeof(IQAccountantSystemContext))]
    [Migration("20220622073352_add-new-tables")]
    partial class addnewtables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IQ.Accountant.System.Entities.Image", b =>
                {
                    b.Property<string>("imageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("IMAGE_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("imageUrl")
                        .HasColumnName("IMAGE_URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("imageId");

                    b.ToTable("IMAGE");
                });

            modelBuilder.Entity("IQ.Accountant.System.Entities.Product", b =>
                {
                    b.Property<int>("productId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PRODUCT_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("productCode")
                        .IsRequired()
                        .HasColumnName("PRODUCT_CODE")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("productPrice")
                        .HasColumnName("PRODUCT_PRICE")
                        .HasColumnType("real");

                    b.Property<float?>("productShipping")
                        .HasColumnName("PRODUCT_SHIPPING")
                        .HasColumnType("real");

                    b.Property<float?>("productTax")
                        .HasColumnName("PRODUCT_TAX")
                        .HasColumnType("real");

                    b.Property<string>("productUnit")
                        .IsRequired()
                        .HasColumnName("PRODUCT_UNIT")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("productId");

                    b.HasIndex("productCode")
                        .IsUnique();

                    b.ToTable("PRODUCT");
                });

            modelBuilder.Entity("IQ.Accountant.System.Entities.ProductImage", b =>
                {
                    b.Property<int>("productImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PRODUCT_IMAGE_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("imageId")
                        .HasColumnName("IMAGE_ID")
                        .HasColumnType("int");

                    b.Property<string>("imageId1")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("productId")
                        .HasColumnName("PRODUCT_ID")
                        .HasColumnType("int");

                    b.HasKey("productImageId");

                    b.HasIndex("imageId1");

                    b.HasIndex("productId");

                    b.ToTable("PRODUCT_IMAGE");
                });

            modelBuilder.Entity("IQ.Accountant.System.Entities.Video", b =>
                {
                    b.Property<string>("videoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("VIDEO_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("videoUrl")
                        .HasColumnName("VIDEO_URL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("videoId");

                    b.ToTable("VIDEO");
                });

            modelBuilder.Entity("IQ.Accountant.System.Entities.productVideo", b =>
                {
                    b.Property<int>("productVideoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("PRODUCT_VIDEO_ID")
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("productId")
                        .HasColumnName("PRODUCT_ID")
                        .HasColumnType("int");

                    b.Property<int>("videoId")
                        .HasColumnName("VIDEO_ID")
                        .HasColumnType("int");

                    b.Property<string>("videoId1")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("productVideoId");

                    b.HasIndex("productId");

                    b.HasIndex("videoId1");

                    b.ToTable("PRODUCT_VIDEO");
                });

            modelBuilder.Entity("IQ.Accountant.System.Entities.ProductImage", b =>
                {
                    b.HasOne("IQ.Accountant.System.Entities.Image", "image")
                        .WithMany("productImages")
                        .HasForeignKey("imageId1");

                    b.HasOne("IQ.Accountant.System.Entities.Product", "product")
                        .WithMany("productImages")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IQ.Accountant.System.Entities.productVideo", b =>
                {
                    b.HasOne("IQ.Accountant.System.Entities.Product", "product")
                        .WithMany("productVideos")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IQ.Accountant.System.Entities.Video", "video")
                        .WithMany("productVideos")
                        .HasForeignKey("videoId1");
                });
#pragma warning restore 612, 618
        }
    }
}
